name: CI Python + Slack Webhook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️ Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ▶️ Ejecutar aplicación
        run: python main.py

      - name: ✅ Ejecutar tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: 📣 Notificar resultado en Slack vía Webhook
        if: always()
        env:
          STATUS: ${{ job.status }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"*CI Notification*
• Repositorio: $GITHUB_REPOSITORY
• Trabajo: $GITHUB_JOB
• Estado: $STATUS
• Commit: $GITHUB_SHA\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
